version: '3'

services:
  api:
    image: ghcr.io/nils-witt/s-splan_api:latest
    environment:
      # API Self
      API_URL: "https://api.example.com"

      # Developer Settings
      APIDOC: "true"

      #PWA
      PWA_URL: "https://pwa.example.com"

      #Notifications

      ##Telegram
      TELEGRAM: "true"
      TELEGRAM_KEY: "TelegramKey"
      TELEGRAM_VALIDATION_URL: "VALIDATION_URL"

      # FCM
      FCM: "false"
      FCM_URL: "https://url_server.firebaseio.com"
      FCM_CREDENTIALS: "/home/node/app/keys/fcm_key.json"

      # WebPush
      WEBPUSH: "false"
      VAPID_PUBLIC: "YOUR_VAPID_PUBIC"
      VAPID_PRIVATE: "YOUR_VAPID_PRIVATE"
      VAPID_SUBJECT: "YOUR_VAPID_SUBJECT"

      # Sendgrid
      SENDGRID: "true"
      SENDGRID_KEY: "SG.BEARER_TOKEN"
      SENDGRID_HOST: "YOUT_SG_HOST"
      SENDGRID_PW_VALIDATION_URL: "SG_VALIDATION_HOST"

      # LDAP
      LDAP: "true"

      LDAP_HOST: "ldap://127.0.0.1:389"
      LDAP_ROOT: "DC=example,DC=com"
      LDAP_DOMAIN: "example"

      LDAP_STUDENTSGROUP: "CN=Students,DC=example,DC=com"
      LDAP_TEACHERGROUP: "CN=Teacher,DC=example,DC=com"

      LDAP_USER: "user"
      LDAP_PASS: "password"

      LDAP_TLS: "false"
      LDAP_CA_PATH: "/home/node/app/keys/ldap-ca.pem"

      # MySQL
      SQL_PORT: 3306
      SQL_HOST: "mysql"
      SQL_USER: "splan"
      SQL_PASS: "pass"
      SQL_DB: "splan"

      # Moodle
      MOODLE: "false"
      MOODLE_URL: "https://moodleServer.example.de/webservice/rest/server.php"
      MOODLE_KEY: "MOODLE_KEY"
    volumes:
    - ./logs/api/:/usr/src/splan/log
    - ./configs/api/keys:/usr/src/splan/keys
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_USER: "splan"
      MYSQL_PASSWORD: ""
      MYSQL_DATABASE: "splan"
    volumes:
      - ./data/database:/var/lib/mysql
  pwa:
    image: ghcr.io/nils-witt/s-plan_pwa:latest
    ports:
      - 8082:80
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mysql
    links:
      - mysql
    depends_on:
      - mysql
  reverseProxy:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./configs/proxy/conf:/etc/nginx
      - ./configs/proxy/certs:/etc/ssl/certs
    links:
      - api
      - pwa
      - phpmyadmin
    depends_on:
      - api
      - pwa
      - phpmyadmin
